version: '2'

services:
  web:
    image: nginx:1.12-alpine
    restart: always
    ports:
      - 81:80
    volumes_from:
      - app

  app:
    image: registry.gitlab.com/cliend/site:latest
    volumes:
      - /app/public
      - /etc/nginx/conf.d