version: '2'

services:
  web:
    image: nginx:1.12-alpine
    restart: always
    ports:
      - 80
    volumes_from:
      - app
    networks:
      - web
    environment:
      VIRTUAL_HOST: cliend.ru
      LETSENCRYPT_HOST: cliend.ru
      LETSENCRYPT_EMAIL: artur@clienddev.ru

  app:
    image: registry.gitlab.com/cliend/site:latest
    volumes:
      - /app/public
      - /etc/nginx/conf.d

networks:
  web:
    external: true